# Generated by Django 5.1.6 on 2025-02-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorField",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineFormType",
            fields=[
                ("form_id", models.AutoField(primary_key=True, serialize=False)),
                ("form_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("blood_group", models.CharField(max_length=5)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.TextField()),
                ("emergency_contact", models.CharField(max_length=100)),
                ("emergency_phone", models.CharField(max_length=20)),
                ("insurance_provider", models.CharField(max_length=100)),
                ("insurance_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("min_stock_level", models.IntegerField()),
                ("current_stock", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="medapp.medicinecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medicinecategory",
            name="form_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="medapp.medicineformtype",
            ),
        ),
        migrations.CreateModel(
            name="MedicineUnit",
            fields=[
                (
                    "barcode",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("manufacturing_date", models.DateField()),
                ("is_dispensed", models.BooleanField(default=False)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="medapp.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmissionRecord",
            fields=[
                ("admission_id", models.AutoField(primary_key=True, serialize=False)),
                ("admission_date", models.DateTimeField()),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                ("room_number", models.CharField(max_length=20)),
                ("admission_reason", models.TextField()),
                ("discharge_summary", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="medapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("condition_name", models.CharField(max_length=100)),
                ("diagnosis_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_histories",
                        to="medapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("prescription_date", models.DateTimeField(auto_now_add=True)),
                ("diagnosis", models.TextField()),
                ("status", models.CharField(max_length=20)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="medapp.admissionrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionDetail",
            fields=[
                (
                    "prescription_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_details",
                        to="medapp.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="medapp.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medapp.admissionrecord",
                    ),
                ),
                (
                    "prescription_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medapp.prescriptiondetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=50)),
                ("joining_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="medapp.doctorfield",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="medapp.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledDose",
            fields=[
                ("dose_id", models.AutoField(primary_key=True, serialize=False)),
                ("scheduled_time", models.DateTimeField()),
                ("dose_amount", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("administered_time", models.DateTimeField(blank=True, null=True)),
                ("reason_if_skipped", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="medapp.medicationschedule",
                    ),
                ),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_doses",
                        to="medapp.staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="medapp.staff",
            ),
        ),
        migrations.CreateModel(
            name="MedicineDispensing",
            fields=[
                ("dispensing_id", models.AutoField(primary_key=True, serialize=False)),
                ("dispensed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensings",
                        to="medapp.medicineunit",
                    ),
                ),
                (
                    "prescription_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensings",
                        to="medapp.prescriptiondetail",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensings",
                        to="medapp.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("generation_date", models.DateTimeField(auto_now_add=True)),
                ("report_type", models.CharField(max_length=50)),
                ("report_content", models.TextField()),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="medapp.admissionrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="medapp.patient",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="medapp.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoseAdministrationLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("vital_signs", models.TextField(blank=True, null=True)),
                ("patient_reaction", models.TextField(blank=True, null=True)),
                ("log_time", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_logs",
                        to="medapp.medicineunit",
                    ),
                ),
                (
                    "dose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="medapp.scheduleddose",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dose_logs",
                        to="medapp.staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admissionrecord",
            name="assistant_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_admissions",
                to="medapp.staff",
            ),
        ),
        migrations.AddField(
            model_name="admissionrecord",
            name="primary_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_admissions",
                to="medapp.staff",
            ),
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=20)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="medapp.medicine",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="medapp.staff",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="medapp.supplier",
                    ),
                ),
            ],
        ),
    ]
