# Generated by Django 5.1.5 on 2025-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
