# Generated by Django 5.1.5 on 2025-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0004_remove_patient_added_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionrecord",
            name="room_number",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="admissionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("admitted", "Admitted"),
                    ("discharged", "Discharged"),
                    ("transferred", "Transferred"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("chronic", "Chronic"),
                ],
                max_length=20,
            ),
        ),
    ]
