# Generated by Django 5.1.5 on 2025-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0005_alter_admissionrecord_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedicalhistory",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("chronic", "Chronic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
