# Generated by Django 5.1.5 on 2025-05-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0006_alter_patientmedicalhistory_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionrecord",
            name="primary_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_admissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
