# Generated by Django 5.1.5 on 2025-05-30 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0007_alter_admissionrecord_primary_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientmedicalhistory",
            old_name="status",
            new_name="status1",
        ),
    ]
