# Generated by Django 5.1.5 on 2025-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0008_rename_status_patientmedicalhistory_status1"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
