# Generated by Django 5.1.5 on 2025-05-31 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0010_remove_patientmedicalhistory_added_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionrecord",
            name="added_by",
        ),
        migrations.AlterField(
            model_name="admissionrecord",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to="medapp.patient",
            ),
        ),
    ]
