# Generated by Django 5.1.5 on 2025-06-02 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0013_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="current_stock",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="min_stock_level",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.AddField(
            model_name="prescription",
            name="assistant_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="dosage",
            field=models.CharField(default="1", max_length=100),
        ),
        migrations.AddField(
            model_name="prescription",
            name="duration_days",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medapp.medicine",
            ),
        ),
        migrations.DeleteModel(
            name="MedicineUnit",
        ),
        migrations.DeleteModel(
            name="PrescriptionItem",
        ),
    ]
