# Generated by Django 5.1.5 on 2025-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0014_remove_prescriptionitem_medicine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="duration_days",
            field=models.IntegerField(null=True),
        ),
    ]
