# Generated by Django 5.1.5 on 2025-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0015_alter_prescription_duration_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="duration_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
